# Generated by Django 5.2.4 on 2025-07-16 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('const_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'constituency',
            },
        ),
        migrations.CreateModel(
            name='LocalBody',
            fields=[
                ('Local_body_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Panchayath', 'Panchayath'), ('Municipality', 'Municipality')], max_length=20)),
                ('old_ward_count', models.IntegerField()),
                ('new_ward_count', models.IntegerField()),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.constituency')),
            ],
            options={
                'db_table': 'localbody',
            },
        ),
        migrations.CreateModel(
            name='MeetingReport',
            fields=[
                ('meeting_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('office_bearer_name', models.CharField(max_length=90)),
                ('designation', models.CharField(max_length=80)),
                ('mobile_number', models.IntegerField()),
                ('meeting_date', models.DateField()),
                ('number_of_attendees', models.IntegerField()),
                ('image1', models.ImageField(upload_to='photos/')),
                ('image2', models.ImageField(upload_to='photos/')),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.constituency')),
                ('local_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.localbody')),
            ],
            options={
                'db_table': 'meeting_report',
            },
        ),
    ]
