# Generated by Django 5.2.4 on 2025-07-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BjpCarousal',
            fields=[
                ('carousal_id', models.AutoField(primary_key=True, serialize=False)),
                ('carousal_image', models.ImageField(upload_to='carousalimage/')),
            ],
            options={
                'db_table': 'carousalImage',
            },
        ),
    ]
