# Generated by Django 5.2.4 on 2025-07-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_bjpcarousal'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'userTable',
            },
        ),
        migrations.DeleteModel(
            name='BjpCarousal',
        ),
    ]
