# Generated by Django 5.2.4 on 2025-07-16 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_usermodel_delete_bjpcarousal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingreport',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.usermodel'),
            preserve_default=False,
        ),
    ]
