# Generated by Django 5.2.4 on 2025-07-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_meetingreport_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingreport',
            name='user',
        ),
        migrations.AddField(
            model_name='meetingreport',
            name='ward_incharge',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meetingreport',
            name='ward_number',
            field=models.IntegerField(null=True),
        ),
    ]
