# Generated by Django 5.2.4 on 2025-07-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_meetingreport_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constituency',
            options={'verbose_name': 'Mandalam', 'verbose_name_plural': 'Mandalams'},
        ),
        migrations.AlterModelTable(
            name='constituency',
            table=None,
        ),
    ]
