# Generated by Django 5.2.4 on 2025-07-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_constituency_options_alter_constituency_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingreport',
            name='designation',
        ),
    ]
